alias vimrc="cd ~/.config/nvim"
alias x="exit"
# alias man="man --nh --nj"
alias less="less -Rn --mouse"
alias pacman="sudo pacman"
alias mv="mv -v"
alias cp="cp -v"
alias rm="rm"
alias ln="ln -v"
alias make="make -j 2"
alias gdb="gdb -q"
alias paruz-yay="PARUZ=yay paruz"
alias paruz-paru="PARUZ=paru paruz"
if test -d "$ANDROID_HOME"
  alias sdkmanager="sdkmanager --sdk_root=$ANDROID_HOME"
end

set -l exaflags "--classify --extended --color-scale --icons --group-directories-first --group --sort=type"
alias e="exa $exaflags"
alias ea="exa $exaflags --all"
alias el="exa $exaflags --long"
alias eal="exa $exaflags --long -a"
alias et="exa $exaflags --tree --level=2"
alias eat="exa $exaflags --tree --level=2 --all"
alias elt="exa $exaflags --tree --level=2 --long"
alias ealt="exa $exaflags --tree --level=2 --all --long"

alias vi="nvim"
alias git-state='git status -s; git submodule status'
